services:
  db:
    image: postgres:15
    container_name: openfinance_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: openfinance_app
    ports:
      - "3333:3333"
    depends_on:
      - db
    environment:
      DB_USERNAME: ${DB_USERNAME} 
      DB_PASSWORD: ${DB_PASSWORD} 
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npx sequelize-cli db:migrate && npm run dev"

volumes:
  pgdata:
